### ISSUE TITLE
Views Sometimes Hidden Before Flipping

### ISSUE THREAD

**Issue by dawsontoth** [mtabini/AFKPageFlipper#8]
# The Problem

When you're reusing views in the flipper, the second and subsequent times they are "flipped" to they are invisible (alpha = 0) until the flip is over.
# When This Happens

The existing project doesn't see this behavior because it makes a new PDFRendererView every time a page is requested.
# Why This Is Happening

Once a view is hidden (you flip away from it) it has an opacity of 0. If you flip back to it, it won't get an opacity of 1 until cleanupFlip is called.
# How To Fix It

My solution was to update "imageByRenderingView" to set the alpha to 1 before it grabs a UIImage, and then to restore the view to whatever alpha it previously had (see the below code snippet). Another approach would be to set the self.newView.alpha to 1 before creating the screenshots of each view.

``` obj-c

- (UIImage *) imageByRenderingView {
    CGFloat oldAlpha = self.alpha;
    self.alpha = 1;
    UIGraphicsBeginImageContext(self.bounds.size);
    [self.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage *resultingImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    self.alpha = oldAlpha;
    return resultingImage;
}
```
# Pull Request

While I know the code above fixes the issue, I wasn't sure if that was the most optimal solution. I can certainly submit a pull request if you like the above approach, or I can do whatever else would be more to your liking. Whatever helps the most.

**Comment by mtabini** [comment]
I think your solution works—can you give me a use-case scenario where UIView reuse would be appropriate (I can think of a few myself, but I want to understand exactly what you're trying to solve).

**Comment by dawsontoth** [comment]
My use case is a bit complicated. I'll simplify what's going on... I have an array of UIViews that I want to use as the pages. Creation of these is an expensive operation, because I have to bridge from JavaScript to Obj-C. So I have to get the array as a one time thing. When the user changes pages, I grab the appropriate view and ask AFKPageFlipper to show it. That means when the user goes back, I'll return the same view.

Unfortunately grabbing a new view on demand isn't working properly in my context, that's why I went through figuring out how to get it to work again.

(This is using Appcelerator Titanium Mobile, if you were wondering.)

**Comment by dawsontoth** [comment]
https://github.com/mtabini/AFKPageFlipper/pull/9
